version: '3'
services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: app_node
    ports:
      - "3002:3002"
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge