FROM ubuntu:latest

#após terminar de subir o container, o comando informado em cmd será executado
# Obs.: O CMD pode ser substituido no momento em que o container está subindo mas o 
# ENTRYPOINT não pode ser substituido mas executará ambos comandos
CMD [ "echo", "Hello World!" ]